// Generated by CoffeeScript 1.8.0
(function() {
  describe('Textarea', function() {
    var $inputor;
    $inputor = null;
    beforeEach(function() {
      var fixture, html;
      html = '<textarea id="inputor" name="textarea" rows="8" cols="40">Stay Foolish, Stay Hungry. @Jobs</textarea>';
      fixture = setFixtures(html);
      return $inputor = fixture.find('#inputor');
    });
    it('Set and get caret pos by given data', function() {
      var caret, inputor;
      inputor = $inputor.get(0);
      caret = new Caret(inputor);
      caret.setPos({
        start: 5,
        end: 12
      });
      expect(caret.getPos().start).toBe(5);
      expect(caret.getPos().end).toBe(12);
      return expect(caret.getPos().text).toBe('Foolish');
    });
    return it('Inert text at pos', function() {
      var caret, inputor;
      inputor = $inputor.get(0);
      caret = new Caret(inputor);
      caret.setPos({
        start: 5,
        end: 12
      });
      caret.insert({
        start: 5,
        end: 12
      }, 'Smart');
      expect(caret.getPos().start).toBe(10);
      expect(caret.getPos().end).toBe(10);
      expect(caret.getPos().text).toBe('');
      return expect($inputor.val()).toBe('Stay Smart, Stay Hungry. @Jobs');
    });
  });

  describe('Input', function() {
    var $inputor;
    $inputor = null;
    beforeEach(function() {
      var fixture, html;
      html = '<input id="inputor" name="input" value="Stay Foolish, Stay Hungry. @Jobs">';
      fixture = setFixtures(html);
      return $inputor = fixture.find('#inputor');
    });
    it('Set and get caret pos by given data', function() {
      var caret, inputor;
      inputor = $inputor.get(0);
      caret = new Caret(inputor);
      caret.setPos({
        start: 5,
        end: 12
      });
      expect(caret.getPos().start).toBe(5);
      expect(caret.getPos().end).toBe(12);
      return expect(caret.getPos().text).toBe('Foolish');
    });
    return it('Inert text at pos', function() {
      var caret, inputor;
      inputor = $inputor.get(0);
      caret = new Caret(inputor);
      caret.setPos({
        start: 5,
        end: 12
      });
      caret.insert({
        start: 5,
        end: 12
      }, 'Smart');
      expect(caret.getPos().start).toBe(10);
      expect(caret.getPos().end).toBe(10);
      expect(caret.getPos().text).toBe('');
      return expect($inputor.val()).toBe('Stay Smart, Stay Hungry. @Jobs');
    });
  });

}).call(this);
